mike_crud:
    resource: "@MikeCRUDBundle/Resources/config/routing.yml"
    prefix:   /CRUD

mike_twig:
    resource: "@MikeTwigBundle/Resources/config/routing.yml"
    prefix:   /MikeTwig

mike_racine:
    resource: "@MikeRacineBundle/Resources/config/routing.yml"
    prefix:   /

